---
openapi: 3.0.1
info:
  title: Geo Location
  version: v1
paths: {}
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
